### ISSUE TITLE
Only xib prevent the iOS7 compatibility

### ISSUE THREAD

**Issue by MessuKilkain** [DZamataev/DZVideoPlayerViewController#2]
AS long as I tested it, the only thing that is not compatible with iOS7 is the use of UIVisualEffect in default xib style. I suggest to remove it from default xib and stil support iOS7.

**Comment by DZamataev** [comment]
True but please forget iOS 7. There is no point in such support. Btw you can always do it with a fork, removing visual effect view. If you want iOS 7 support out of the box -> use version 0.1.0.
