### ISSUE TITLE
Video on AWS S3 doesn't play automatically after the buffering starts and loads the sufficient playable stream

### ISSUE THREAD

**Issue by singhamit089** [DZamataev/DZVideoPlayerViewController#4]
Once I have started playing the video using the exact sample code mentioned in the readme, the video plays successfully, but the only problem is, once it starts buffering and when the stream is available to play it doesn't play automatically. One need to manually press the play button to  to stop the activity indicator's spinner and resume playing the video.

**Comment by DZamataev** [comment]
@singhamit089 Hi! Check out my latest commit with a playback from valid .mp4 URL. I am not having the issue you pointed.
Debug line `259` in `DZVideoPlayerViewController` class to check why playback does not start automatically if you set so by passing YES as the `playAutomatically` argument.

**Comment by singhamit089** [comment]
@DZamataev I already have set `playAutomatically` as `YES`. The mp4 file I am trying play is stored on Amazon's S3 is there any way to check if the mp4 is valid ? could you help me with it ?

**Comment by DZamataev** [comment]
Yeah, just try to play it in your web browser.
You may give me your URL to debug or debug it on your own.

**Comment by singhamit089** [comment]
@DZamataev Turns out, there was a meta data issue, the Content-Type wasn't set to video/mp4 on AWS S3, I just did and it plays in the browser now, but the above issue still exist with the library. What do you think I might be doing wrong ?

**Comment by singhamit089** [comment]
@DZamataev I just tested the Example provided with this library the above mentioned issue persist over there too.

**Comment by singhamit089** [comment]
Okay, you can close this issue, here is the answer :
I have been trying to stream my videos directly from AWS S3 which is I kinda stupid. I will have to use Amazon Cloud Front for best results or will have setup one video streaming server.

**Comment by DZamataev** [comment]
Hi!
Actually, I’ve just tested your link with the example project and it works as expected. Playback starts immediately.
You may want to comment on this and close the issue.

**Comment by DZamataev** [comment]
Yea, ok. Could you please leave a comment and close the issue.

2016-08-22 11:33 GMT+03:00 Amit Singh <notifications@github.com>:
